
name: "Deploy to Google Cloud Run"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Get Github Actions IP
        id: ip
        uses: haythem/public-ip@v1.2
      
      - name: "SSH"
        run: |
          gcloud compute firewall-rules update amc-creative-edge-firewall --direction=INGRESS --action=ALLOW --rules=tcp:22 --source-ranges=${{ steps.ip.outputs.ipv4 }}/32 
          gcloud compute ssh --zone "us-central1-a" "amc-demo" --command="mkdir actions"  --project "us-gcp-ame-its-450d9-npd-1"
          gcloud compute ssh --zone "us-central1-a" "amc-demo" --command="ls -a"  --project "us-gcp-ame-its-450d9-npd-1"
            


            

    
