
name: "Deploy to Google Cloud Run"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Login to Artifact Registry
        run: |
            docker build -t us-central1-docker.pkg.dev/qwiklabs-gcp-01-aae3e5aa7e45/cloudrun/backend:v2 .

      - name: Push image
        run: docker push us-central1-docker.pkg.dev/qwiklabs-gcp-01-aae3e5aa7e45/cloudrun/backend:v2

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          image: us-central1-docker.pkg.dev/qwiklabs-gcp-01-aae3e5aa7e45/cloudrun/backend:v2
          service: hello
          region: us-central1
            

    
