name: "Deploy to Google Cloud Run"

on:
  push:
    branches:
      - main

jobs:
  check_disk_space:
    runs-on: ubuntu-latest
    steps:
      - name: Check Disk Space
        run: |
          df -h /

      - name: Delete huge unnecessary tools folder 
        run: rm -rf /opt/hostedtoolcache

      - name: Check Disk Space1
        run: |
          df -h /
          
        
  
